export const copy = {
  it: {
    deleteConfirm: 'Eliminare questo elemento? Potrai ripristinarlo dal Cestino entro 30 giorni.',
    settings: 'Impostazioni',
    expand: 'Espandi pannello',
    reduce: 'Riduci pannello',
    tasks: 'Attività',
    projects: 'Progetti',
    today: 'Oggi',
    inbox: 'Inbox',
    upcoming: 'Prossime',
    project: 'Per progetto',
    tag: 'Per etichetta',
    board: 'Kanban',
    calendar: 'Calendario scadenze',
    completed: 'Completate',
    trash: 'Cestino',
    review: 'Revisione settimanale',
    newTask: 'Nuova attività',
    newSubtask: 'Aggiungi sottoattività',
    subtaskProgress: 'Sottoattività dirette: {done}/{total} completate',
    newProject: 'Nuovo progetto',
    createProject: 'Crea il primo progetto',
    createTask: 'Aggiungi un’attività',
    newArea: 'Nuova area',
    newMilestone: 'Nuova tappa',
    newFilter: 'Salva filtro',
    capture: 'Cattura un pensiero',
    saveAnother: 'Salva e aggiungi un’altra',
    captureSaving: 'Salvataggio sul dispositivo…',
    captureSaved: 'Attività salvata sul dispositivo. Puoi aggiungerne un’altra.',
    captureHint: 'Es. pagare bolletta domani alle 17 #casa p1',
    title: 'Titolo',
    notes: 'Note Markdown',
    goal: 'Obiettivo',
    status: 'Stato',
    priority: 'Priorità',
    dueDate: 'Scadenza',
    dueAt: 'Ora (24 h)',
    startDate: 'Data di inizio',
    estimate: 'Stima (minuti)',
    actual: 'Tempo effettivo (minuti)',
    tags: 'Etichette separate da virgole',
    projectId: 'Progetto',
    parentId: 'Attività principale',
    recurrence: 'Ricorrenza RRULE',
    timezone: 'Fuso orario',
    reminders: 'Promemoria (date ISO, uno per riga)',
    reminderHint: 'Le date vengono salvate; le notifiche push arriveranno in M8.',
    attachments: 'Allegati: nome e URL HTTPS (uno per riga, separati da |)',
    areaId: 'Area',
    deadline: 'Termine',
    query: 'Filtro (es. p1 & due:this week & #work)',
    color: 'Colore',
    save: 'Salva',
    cancel: 'Annulla',
    close: 'Chiudi',
    edit: 'Modifica',
    remove: 'Elimina',
    restore: 'Ripristina',
    undo: 'Annulla eliminazione',
    complete: 'Completa',
    reopen: 'Riapri',
    todo: 'Da fare',
    doing: 'In corso',
    done: 'Completato',
    active: 'Attivo',
    paused: 'In pausa',
    none: 'Nessuno',
    search: 'Cerca o filtra attività',
    empty: 'Qui c’è spazio per il prossimo passo.',
    emptyHint: 'Aggiungi un’attività: sarà disponibile anche offline.',
    saved: 'Salvato sul dispositivo',
    error: 'Operazione non riuscita. Controlla i campi, i collegamenti e la sincronizzazione.',
    invalid: 'Controlla titolo, data e ricorrenza.',
    select: 'Seleziona',
    selected: 'selezionate',
    selectAll: 'Seleziona tutte le attività filtrate',
    bulkActions: 'Azioni sulle attività selezionate',
    bulkSaving: 'Salvataggio delle attività selezionate…',
    bulkSaved: '{count} attività salvate sul dispositivo',
    bulkFailed: '{count} attività non salvate: restano selezionate per riprovare.',
    bulkDeleteConfirm:
      'Eliminare le {count} attività selezionate? Potrai ripristinarle dal Cestino entro 30 giorni.',
    clear: 'Deseleziona',
    move: 'Sposta',
    up: 'Sposta sopra',
    down: 'Sposta sotto',
    refresh: 'Aggiorna',
    stalled: 'Progetti fermi da 7 giorni',
    overdue: 'Attività scadute',
    processInbox: 'Da organizzare in Inbox',
    progress: 'avanzamento',
    milestones: 'Tappe',
    areas: 'Aree della vita',
    filters: 'Filtri salvati',
    all: 'Tutte',
    palette: 'Cerca e comandi',
    paletteHint: 'Cerca attività e progetti o scegli un’azione',
    shortcuts: 'Scorciatoie',
    shortcutHint:
      'N: nuova attività · Ctrl/Cmd+K: cerca · ?: aiuto · Esc: chiudi. Su mobile: scorri a destra per completare, a sinistra per modificare; tieni premuto per selezionare.',
    month: 'Mese',
    previous: 'Precedente',
    next: 'Successivo',
    noDue: 'Senza scadenza',
    preview: 'Anteprima',
    metadata: 'Metadati allegati',
    task: 'Attività',
    area: 'Area',
    milestone: 'Tappa',
    filter: 'Filtro',
    deleteHint: 'Le attività eliminate restano recuperabili per 30 giorni.',
    dragHint: 'Trascina per spostare; usa Modifica o i pulsanti sopra/sotto da tastiera.',
    reviewHint: 'Rivedi i progetti fermi, scegli le priorità e organizza gli elementi in Inbox.',
    ready: 'Pronto per il tuo prossimo passo.',
    pending: 'In attesa di sincronizzazione',
    loading: 'Caricamento…',
    open: 'Apri',
    saveFirst: 'Scartare le modifiche non salvate?',
    searchProjects: 'Cerca progetti per titolo o obiettivo',
    allStatuses: 'Tutti gli stati',
    emptyProjectHint: 'Crea un progetto e suddividi il tuo obiettivo in attività e tappe.',
    noResults: 'Nessun progetto corrisponde ai filtri.',
    noResultsHint: 'Prova un altro termine oppure azzera i filtri per vedere tutti i progetti.',
    resetFilters: 'Azzera filtri',
    weekStart: 'La settimana inizia dalle preferenze',
    more: 'Altre azioni',
  },
  en: {
    deleteConfirm: 'Delete this item? You can restore it from Trash within 30 days.',
    settings: 'Settings',
    expand: 'Expand sheet',
    reduce: 'Reduce sheet',
    tasks: 'Tasks',
    projects: 'Projects',
    today: 'Today',
    inbox: 'Inbox',
    upcoming: 'Upcoming',
    project: 'By project',
    tag: 'By tag',
    board: 'Kanban',
    calendar: 'Deadline calendar',
    completed: 'Completed',
    trash: 'Trash',
    review: 'Weekly review',
    newTask: 'New task',
    newSubtask: 'Add subtask',
    subtaskProgress: 'Direct subtasks: {done}/{total} completed',
    newProject: 'New project',
    createProject: 'Create your first project',
    createTask: 'Add a task',
    newArea: 'New area',
    newMilestone: 'New milestone',
    newFilter: 'Save filter',
    capture: 'Capture a thought',
    saveAnother: 'Save and add another',
    captureSaving: 'Saving on this device…',
    captureSaved: 'Task saved on this device. You can add another.',
    captureHint: 'E.g. pay bill tomorrow at 5pm #home p1',
    title: 'Title',
    notes: 'Markdown notes',
    goal: 'Goal',
    status: 'Status',
    priority: 'Priority',
    dueDate: 'Due date',
    dueAt: 'Time (24 h)',
    startDate: 'Start date',
    estimate: 'Estimate (minutes)',
    actual: 'Actual time (minutes)',
    tags: 'Comma-separated tags',
    projectId: 'Project',
    parentId: 'Parent task',
    recurrence: 'Recurrence RRULE',
    timezone: 'Time zone',
    reminders: 'Reminders (ISO dates, one per line)',
    reminderHint: 'Dates are saved; push notifications arrive in M8.',
    attachments: 'Attachments: name and HTTPS URL (one per line, separated by |)',
    areaId: 'Area',
    deadline: 'Deadline',
    query: 'Filter (e.g. p1 & due:this week & #work)',
    color: 'Color',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    edit: 'Edit',
    remove: 'Delete',
    restore: 'Restore',
    undo: 'Undo deletion',
    complete: 'Complete',
    reopen: 'Reopen',
    todo: 'To do',
    doing: 'In progress',
    done: 'Completed',
    active: 'Active',
    paused: 'Paused',
    none: 'None',
    search: 'Search or filter tasks',
    empty: 'Room for your next step.',
    emptyHint: 'Add a task: it will also be available offline.',
    saved: 'Saved on this device',
    error: 'Could not save. Check fields, references and synchronization.',
    invalid: 'Check title, date and recurrence.',
    select: 'Select',
    selected: 'selected',
    selectAll: 'Select all filtered tasks',
    bulkActions: 'Actions for selected tasks',
    bulkSaving: 'Saving selected tasks…',
    bulkSaved: '{count} tasks saved on this device',
    bulkFailed: '{count} tasks could not be saved: they remain selected for retry.',
    bulkDeleteConfirm:
      'Delete the {count} selected tasks? You can restore them from Trash within 30 days.',
    clear: 'Clear selection',
    move: 'Move',
    up: 'Move up',
    down: 'Move down',
    refresh: 'Refresh',
    stalled: 'Projects stalled for 7 days',
    overdue: 'Overdue tasks',
    processInbox: 'Inbox to organize',
    progress: 'progress',
    milestones: 'Milestones',
    areas: 'Life areas',
    filters: 'Saved filters',
    all: 'All',
    palette: 'Search and commands',
    paletteHint: 'Search tasks and projects or choose an action',
    shortcuts: 'Keyboard shortcuts',
    shortcutHint:
      'N: new task · Ctrl/Cmd+K: search · ?: help · Esc: close. On mobile: swipe right to complete, left to edit; hold to select.',
    month: 'Month',
    previous: 'Previous',
    next: 'Next',
    noDue: 'No due date',
    preview: 'Preview',
    metadata: 'Attachment metadata',
    task: 'Task',
    area: 'Area',
    milestone: 'Milestone',
    filter: 'Filter',
    deleteHint: 'Deleted tasks can be restored for 30 days.',
    dragHint: 'Drag to move; use Edit or the up/down buttons with a keyboard.',
    reviewHint: 'Review stalled projects, choose priorities and organize your inbox.',
    ready: 'Ready for your next step.',
    pending: 'Waiting to sync',
    loading: 'Loading…',
    open: 'Open',
    saveFirst: 'Discard unsaved changes?',
    searchProjects: 'Search projects by title or goal',
    allStatuses: 'All statuses',
    emptyProjectHint: 'Create a project and break your goal into tasks and milestones.',
    noResults: 'No projects match the filters.',
    noResultsHint: 'Try another search or reset the filters to see all projects.',
    resetFilters: 'Reset filters',
    weekStart: 'Week starts according to preferences',
    more: 'More actions',
  },
};
export type Copy = typeof copy.it;
